### ISSUE TITLE
Private/Public data

### ISSUE THREAD

**Issue by jgeddes82** [mjcolebank/CDG_NCSU#3]
Mette asked me to make the data for a paper public, but if possible, upload the key for which data is which and make that private. Is there a way to do that? The data is currently uploaded, but the key is not.

**Comment by mjcolebank** [comment]
Hi Justen,

Unfortunately not. There is a discussion here [https://github.community/t/can-i-make-parts-of-my-private-repository-public/3112/3](url) about why that isn't possible. Long-story short, git was designed so that people who download a repo get **all** parts of the repository. So you can't have part of a public repository private 😞
